### PR TITLE
Add Electricraft

### PR DESCRIPTION
**Pull request by Maxwell-lt**
Now ReactorCraft will be viable

### CODE REVIEW

**Comment by Baughn** [comment]
I would honestly prefer less Reika rather than more. Electricraft has a rather high TPS impact; far far higher than Eln for the same network size.

**Comment by Baughn** [comment]
In my experience, it scales as about N*M; N being the number of power producers/consumers, M being the number of wires. I haven't looked closely at the code to figure out why that is.

So it's okay if you build a minimal system, but can rapidly get out of hand.

**Comment by Maxwell-lt** [comment]
The main reason I want Electricraft is so that power storage is viable. Bedrock Coils can only provide 67MW to a single machine, and even T5 Magnetostatics (besides being really inefficient and consuming LN2) can only provide 268MW to a single machine. When I'm producing ~835MW with a starter reactor using water for steam, those numbers are not very good.

If it would deter lag, using Rotarycraft shaft power splitters at major intersections would only have the downside of space consumption, and is a path I could certainly take. Also, long wire runs are entirely unnecessary with Chromaticraft World Rifts, so that should keep M low.

**Comment by Castone22** [comment]
So basically if we do add it keep in mind that I'm going to be VERY heavy handed with system optimization.  Forever given you and burper have been compliant with most of my suggestions in the past, I'm inclined to trust you.

**Pull request merged**
